name: 'Run function'
description: 'run external js and return result'
inputs:
  file: 
    description: 'file to run'
    required: true    
  tag: # branch name
    description: 'branch name'
    required: true
outputs:
  result: # output will be available to future steps
    description: 'Test result'
runs:
  using: 'node12'
  main: 'dist/index.js'
